import os

from app.orchestration.patchpilot_context import (
    PatchPilotContext
)


# Service for loading and managing PatchPilot's configuration context.
# It primarily reads environment variables to set up the execution context.
class ConfigurationService:
    """
    Service for loading and managing PatchPilot's configuration context.
    It primarily reads environment variables to set up the execution context,
    providing defaults for local development.
    """ # pylint: disable=duplicate-code

    @staticmethod
    def load_context() -> PatchPilotContext:
        """
        Loads the PatchPilot execution context from environment variables.
        Provides default values for local development if environment variables are not set.

        Returns:
            PatchPilotContext: An instance of PatchPilotContext populated with configuration.
        """

        # Retrieve GitLab CI pipeline ID from environment, defaulting to "local-dev" for local runs.
        pipeline_id = os.getenv(
            "CI_PIPELINE_ID",
            "local-dev"
        )

        branch_prefix = os.getenv(
            "PATCHPILOT_BRANCH_PREFIX",
            "patchpilot/remediation"
        )

        # Construct the remediation branch name using the prefix and pipeline ID.
        remediation_branch = (
            f"{branch_prefix}-{pipeline_id}"
        )

        # Define the root directory for the ephemeral workspace.
        workspace_root = (
            f"/tmp/patchpilot/{pipeline_id}"
        )
        
        # Define the path where the target repository will be cloned within the workspace.
        target_repo_path = (
            f"{workspace_root}/target-repo"
        )

        # Return a PatchPilotContext instance with all loaded and derived configuration.
        return PatchPilotContext(

            # -----------------------------
            # GitLab Pipeline Context
            # ----------------------------- # pylint: disable=duplicate-code

            project_id=os.getenv(
                # GitLab project ID from environment.
                "CI_PROJECT_ID",
                "local-project"
            ),

            pipeline_id=pipeline_id,

            project_url=os.getenv(
                # URL of the GitLab project from environment.
                "CI_PROJECT_URL",
                ""
            ),

            default_branch=os.getenv(
                # Default branch of the target repository (e.g., 'main' or 'master') from environment.
                "CI_DEFAULT_BRANCH",
                "master"
            ),

            # -----------------------------
            # Execution Config
            # -----------------------------

            dry_run=(
                os.getenv(
                    "PATCHPILOT_DRY_RUN",
                    # If 'true', no actual Git operations (push, MR creation) will occur. Defaults to 'false'.
                    "false"
                ).lower()
                == "true"
            ),

            max_retries=int(
                os.getenv(
                    "PATCHPILOT_MAX_RETRIES",
                    # Maximum number of attempts for the remediation loop. Defaults to 10.
                    "10"
                )
            ),

            # Prefix for remediation branches (e.g., 'patchpilot/remediation-').
            branch_prefix=branch_prefix,

            # -----------------------------
            # Runtime State
            # -----------------------------

            workspace_root=workspace_root, # Root directory for the ephemeral workspace.

            # Path to the cloned target repository within the workspace.
            target_repo_path=target_repo_path,

            # The full name of the remediation branch to be created.
            remediation_branch=
                remediation_branch,

            # -----------------------------
            # Vulnerability Report
            # ----------------------------- # pylint: disable=duplicate-code

            # Expected filename for the vulnerability report artifact.
            # This file is typically generated by a CI/CD scanner.
            vulnerability_report_path=(
                "gl-dependency-scanning-report.json"
            )
        )